package-lock.json
package.json
public/index.html
src/client/components/landing/LandingBody.jsx
src/client/styles/main.less

Ticket | Title
---|---
#11 | [web] Update landing page
Added a temporary typeform for users to sign up to a mailing list. The results are stored in an excel sheet on the myriade drive, under the web folder.

Added sign up form on landing page

---

src/client/components/landing/LandingBody.jsx
src/client/styles/main.less

Ticket | Title
---|---
#11  | [web] Update landing page 
This PR adds an FAQ section to the website and applies some minor design changes
Used React Bootstrap's accordion element with cards to create an interactive dropdown UI for some basic questions about Myriade.
Changed some font colors and sizes.

Added FAQ Section to website

---

src/client/pages/SignupPage.jsx
src/client/styles/pages/Signup.less

Ticket | Title
---|---
#15 | Change to signup form
#16 | Change to signup form part 2
1. In the signup form, next to the "monero wallet address" title, there is now a "What's this?" badge which will hyperlink to this: https://medium.com/@paul_70212/how-to-get-yourself-a-monero-xmr-wallet-address-2edb75a0a575
2. Updated placeholders in signup UI for clarity

updating signup UI

---

src/client/components/dashboard/Mine.jsx
src/client/styles/components/dashboard/Mine.less
src/client/utils/xmr_config.js

Ticket | Title
---|---
#4 | Finalize Miner dashboard
Added instructions for downloading XMRig and generating configuration `config.json` with minerId and address in order to work with XMRig.
* Simple instructions for Alpha release with XMRig
* Downloadable `config.json` file customized for the miner and XMRig

[web#4] Finalize miner dashboard (Start Mining Page)

---

src/client/components/dashboard/Analytics.jsx
src/client/styles/components/dashboard/Analytics.less

Ticket | Title
---|---
fixes #14  | [web] Fix lack of responsiveness
- Cleaned up html for analytics page
- Added dynamic rendering of elements for different screen sizes. One needs to reload if they are loading the small screen for the first time, else the user will use React Bootstrap's CardDeck responsive layout.
Large:
Medium:
Small:

[web] dynamic analytics views

---

src/client/components/dashboard/Analytics.jsx
src/client/components/dashboard/Gameroom.jsx
src/client/layers/AuthLayer.jsx
src/client/pages/Dashboard.jsx
src/client/styles/components/dashboard/Analytics.less
src/client/styles/components/dashboard/Gameroom.less
src/client/styles/shards/_card.scss

Ticket | Title
---|---
fixes #37 | Design Changes on Mining Dashboard
As requested by @sqphoenix , this PR:
- Changes card backgrounds on the landing page
- Realigns the text in the card
- Changes the text in the cards

[web] Updating landing page design

---

src/client/components/landing/LandingBody.jsx
src/client/components/landing/LandingFooter.jsx
src/client/pages/LandingPage.jsx
src/client/styles/components/landing/main.less

Ticket | Title
---|---
fixes #41 | [web] Embed Myriade Explainer Video in homepage
fixes #40 | [web] change date in footer
fixes #39 | [web] Update Discord invite link in footer
As per @sqphoenix 's request, this PR does the following:
- Adds video to landing page
- Updates year and Discord link in footer
In addition, this PR updated the spacing between website sections, and put the mailing list form in a Jumbotron.

[web] Updates to the landing page

---

src/client/components/landing/LandingFooter.jsx

Ticket | Title
---|---
fixes #44  | [web] Add linkedin link
Description in title.

[web] added Linkedin to landing page

---

src/client/components/dashboard/games/Raffle.jsx
src/client/pages/LoginPage.jsx
src/client/pages/SignupPage.jsx

This is an intermediary commit.
Changes made in this PR:
- Fixed the typo for form autocomplete fields
- Added the raffle component, that will be displayed once the user selects the raffle option from the gameroom view. I'm currently working on the routing within that component.

[web] Fixed autocomplete bug and added raffle component

---

src/client/App.jsx
src/client/components/dashboard/Analytics.jsx
src/client/components/dashboard/Gameroom.jsx
src/client/components/dashboard/games/Grid.jsx
src/client/components/dashboard/games/Raffle.jsx
src/client/components/dashboard/games/api.json
src/client/layers/AuthLayer.jsx
src/client/styles/components/common/Theme.less
src/client/styles/components/dashboard/Gameroom.less

Ticket | Title
---|---
fixes #54  | [web] Improve Game Room UI
#5 | [Web] Implement Game Room view
This PR accomplishes the follwing:
- Set up routing within the gameroom component so that the user can navigate to a new view for each game. <Link> destinations are currently hardcoded. If @hanburger97 could show me how to access the current href that would be great :smile: 
- Updated the scrollbar to match the theme
- Added descriptions for the gameroom, drawings, and grid components
- Added a temp **api.json** file to be used in the gameroom component., Located in `web/src/client/components/dashboard/games/api.json`. @andyjung-dev this is probably what web will expect from the API.
- Finalize web UI for raffles component

[web] Game Room Enhancements

---

public/index.html

Ticket | Title
---|---
fixes #52 | [web] Add Chatra 
Added chatra component. It shows on all parts of the page.

[web] Added chatra

---

src/client/components/dashboard/Mine.jsx

Ticket | Title
---|---
fixes #62 | [web] Adding in XMRIG install tutorial video
Adds a video tutorial as requested in the issue. The video appears in a modal.

[web] added windows video tutorial

---

src/client/components/dashboard/Mine.jsx
src/client/components/dashboard/Support.jsx
src/client/styles/components/dashboard/Gameroom.less
src/client/styles/components/dashboard/Support.less

Ticket | Title
---|---
fixes #46 | [web] Add in Support Tab
Adds a support tab as requested in #46. Cards move up on hover.

[web] Added support tab

---

src/client/App.jsx
src/client/components/common/CookiesToast.jsx
src/client/components/dashboard/Gameroom.jsx
src/client/components/dashboard/Mine.jsx
src/client/components/dashboard/Support.jsx
src/client/pages/LandingPage.jsx
src/client/styles/components/dashboard/Gameroom.less
src/client/styles/components/dashboard/Support.less
src/client/styles/main.less

Ticket | Title
---|---
fixes #21 | [web] Add cookies banner to be GDPR compliant
Added a banner as requested by @sqphoenix . The user's preference for cookies is stored as **cookiesAllowed** in localstorage on the client. If there is no preference set, the component waits 5 seconds after mounting before prompting the user.
Also made the landing page alert dismissable.

[web] Added cookies banner

---

src/client/components/common/CookiesToast.jsx
src/client/components/common/Navbar.jsx
src/client/layers/AuthLayer.jsx
src/client/styles/components/common/Common.less
src/client/styles/components/common/Navbar.less
src/client/styles/main.less

Fixed a bug related to the cookies toast, where the element blocked parts of the page even though it was invisible.

[web] Fix bug with cookies toast

---

src/client/components/common/Link.jsx
src/client/components/dashboard/Analytics.jsx
src/client/components/dashboard/Support.jsx
src/client/pages/Dashboard.jsx

Ticket | Title
---|---
fixes #70 | [web] Resolution link placement bug
- Fixes the bug outlined in #70 . This was done by having automatically scaling font sizes, similar to the analytics cards seciton.
- Fixes a styling bug on the support tab, where the cards would obstruct the description.

[web] Fix syling bugs

---

src/client/utils/config.js

In https://github.com/myriadeinc/web/pull/73 I forgot to reset the config variable for auth to poin to our development URL. This PR reverts that.

[web] Revert config change

---

src/client/components/dashboard/Mine.jsx
src/client/pages/LoginPage.jsx
src/client/pages/SignupPage.jsx

Ticket | Title
---|---
fixes #76 | [web] Add sign in link on sign up page
Added link to login from signup, and made the linux instructions button point via Link component.

[web] Fixing links

---

src/client/components/common/Buttons.jsx
src/client/components/common/Navbar.jsx
src/client/components/landing/LandingBody.jsx
src/client/pages/Dashboard.jsx
src/client/pages/LandingPage.jsx
src/client/styles/components/landing/main.less

Ticket | Title
---|---
fixes #78 | [web] Hompeage Design Changes
Small design changes as requested by @sqphoenix. Buttons look different, and a timestamp is added for the video component. The contents for the mining alert are also updated as per the request.

[web] Landing design changes

---

src/client/components/dashboard/Mine.jsx

Ticket | Title
---|---
fixes #82 | [web] Un-minify the config files (non urgent)

windows video on by default, json for config now prettified

---

src/client/pages/SignupPage.jsx
src/client/styles/pages/Login.less
src/client/styles/pages/Signup.less

Ticket | Title
---|---
#91 | [web] Signup page mobile fix
Fixed bug where the signup was not mobile friendly

[web] Fixed responsive signup

---

src/client/pages/SignupPage.jsx
src/client/styles/pages/Signup.less

Ticket | Title
---|---
#94 | [web] Change Signup Page Text
- moved myriade wallet field to bottom
- made asterisks red and larger font
- updated signup page text

[web] Minor signup change

---

package-lock.json
package.json
public/index.html
public/myriadewebsite.css
src/client/App.jsx
src/client/components/common/Buttons.jsx
src/client/components/common/Link.jsx
src/client/components/dashboard/Mine.jsx
src/client/components/landing/LandingBody.jsx
src/client/index.js
src/client/styles/components/landing/main.less

Ticket | Title
---|---
#96 | [web] Google Analytics site tag pages
Added support to track a site's history with google analytics.
Added react google analytics to the app component as outlined here: https://levelup.gitconnected.com/using-google-analytics-with-react-3d98d709399b

[web] Analytics tracking pages

---

src/client/pages/Dashboard.jsx

#Fixed miner info update bug - ALPHA-12
Miner information does not show in component mount/load component is src/client/components/dashboard/Analytics.jsx
Some miner data is being retrieved after miner info is set in componentDidMount() of the Dashboard component.
Temp Fix: forceUpdate() after retrieving data that belongs to the miner object.
Better Fix: await each call and update miner info in one shot.

Fixed miner info update bug - ALPHA-12

---

src/client/components/dashboard/Analytics.jsx
src/client/styles/components/dashboard/Gameroom.less

#Fixed card flickering in game rooms
Cards would flicker on mouseover in the game room and giveaways.
Added backface visibilty: hidden to the .less file for the game room.

Fixed card flickering in game rooms

---

src/client/components/landing/LandingFooter.jsx

Added github icon link to footer - ALPHA-24

---

src/client/components/dashboard/Mine.jsx

Added download buttons for the XMRig miner to the windows/linux pages - ALPHA-28

---

src/client/components/dashboard/Mine.jsx

Changed miner install vid + removed mining pool alert - ALPHA-31

---

src/client/pages/SignupPage.jsx

Added (optional) to address and fixed margin on inputs - ALPHA-32

---

src/client/pages/SignupPage.jsx

Autocomplete email instead of username - ALPHA-30

---

src/client/styles/components/dashboard/Mine.less

Made start mining pages scrollbox the same size as game room - ALPHA-34

---

src/client/components/dashboard/LineChart.jsx

Historical metrics uses real data - ALPHA-38

---

src/client/components/dashboard/games/Raffle.jsx

Added raffle validation in front-end and fixed time - ALPHA-44

---

src/client/components/dashboard/Withrdraw.jsx

Added UUID to withdrawal emails - BETA-53
